export const ANALYTICS_EVENT_TYPES = [
  'PAGE_VIEW',
  'PRODUCT_VIEW',
  'ADD_TO_CART',
  'ADD_TO_WISHLIST',
  'CHECKOUT_INITIATED',
  'PURCHASE_SUCCESS',
  'SEARCH_USED',
  'NEW_CUSTOMER_REGISTERED',
  'CONTACT_SUBMITTED',
  'NEWSLETTER_JOINED',
] as const

export type AnalyticsEventType = (typeof ANALYTICS_EVENT_TYPES)[number]
