/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    pages: Page;
    posts: Post;
    media: Media;
    categories: Category;
    users: User;
    services: Service;
    products: Product;
    career: Career;
    'contact-submissions': ContactSubmission;
    employees: Employee;
    leads: Lead;
    'newsletter-subscriptions': NewsletterSubscription;
    'seo-keywords': SeoKeyword;
    'issue-reports': IssueReport;
    'chat-summaries': ChatSummary;
    redirects: Redirect;
    forms: Form;
    'form-submissions': FormSubmission;
    search: Search;
    'payload-kv': PayloadKv;
    'payload-jobs': PayloadJob;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    pages: PagesSelect<false> | PagesSelect<true>;
    posts: PostsSelect<false> | PostsSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    services: ServicesSelect<false> | ServicesSelect<true>;
    products: ProductsSelect<false> | ProductsSelect<true>;
    career: CareerSelect<false> | CareerSelect<true>;
    'contact-submissions': ContactSubmissionsSelect<false> | ContactSubmissionsSelect<true>;
    employees: EmployeesSelect<false> | EmployeesSelect<true>;
    leads: LeadsSelect<false> | LeadsSelect<true>;
    'newsletter-subscriptions': NewsletterSubscriptionsSelect<false> | NewsletterSubscriptionsSelect<true>;
    'seo-keywords': SeoKeywordsSelect<false> | SeoKeywordsSelect<true>;
    'issue-reports': IssueReportsSelect<false> | IssueReportsSelect<true>;
    'chat-summaries': ChatSummariesSelect<false> | ChatSummariesSelect<true>;
    redirects: RedirectsSelect<false> | RedirectsSelect<true>;
    forms: FormsSelect<false> | FormsSelect<true>;
    'form-submissions': FormSubmissionsSelect<false> | FormSubmissionsSelect<true>;
    search: SearchSelect<false> | SearchSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-jobs': PayloadJobsSelect<false> | PayloadJobsSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  fallbackLocale: null;
  globals: {
    header: Header;
    footer: Footer;
    'site-settings': SiteSetting;
    'homepage-content': HomepageContent;
    'about-page-content': AboutPageContent;
    'posts-page-content': PostsPageContent;
    'careers-page-content': CareersPageContent;
    'contact-page-content': ContactPageContent;
    'products-page-content': ProductsPageContent;
    'services-page-content': ServicesPageContent;
    'sectors-content': SectorsContent;
    'seo-settings': SeoSetting;
  };
  globalsSelect: {
    header: HeaderSelect<false> | HeaderSelect<true>;
    footer: FooterSelect<false> | FooterSelect<true>;
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
    'homepage-content': HomepageContentSelect<false> | HomepageContentSelect<true>;
    'about-page-content': AboutPageContentSelect<false> | AboutPageContentSelect<true>;
    'posts-page-content': PostsPageContentSelect<false> | PostsPageContentSelect<true>;
    'careers-page-content': CareersPageContentSelect<false> | CareersPageContentSelect<true>;
    'contact-page-content': ContactPageContentSelect<false> | ContactPageContentSelect<true>;
    'products-page-content': ProductsPageContentSelect<false> | ProductsPageContentSelect<true>;
    'services-page-content': ServicesPageContentSelect<false> | ServicesPageContentSelect<true>;
    'sectors-content': SectorsContentSelect<false> | SectorsContentSelect<true>;
    'seo-settings': SeoSettingsSelect<false> | SeoSettingsSelect<true>;
  };
  locale: null;
  user: User & {
    collection: 'users';
  };
  jobs: {
    tasks: {
      schedulePublish: TaskSchedulePublish;
      inline: {
        input: unknown;
        output: unknown;
      };
    };
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: string;
  title: string;
  /**
   * Arabic title for the page when Arabic language is selected
   */
  titleAr?: string | null;
  hero: {
    type: 'none' | 'highImpact' | 'mediumImpact' | 'lowImpact';
    richText?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
    links?:
      | {
          link: {
            type?: ('reference' | 'custom') | null;
            newTab?: boolean | null;
            reference?:
              | ({
                  relationTo: 'pages';
                  value: string | Page;
                } | null)
              | ({
                  relationTo: 'posts';
                  value: string | Post;
                } | null);
            url?: string | null;
            label: string;
            /**
             * Arabic label for the link when Arabic language is selected
             */
            labelAr?: string | null;
            /**
             * Choose how the link should be rendered.
             */
            appearance?: ('default' | 'outline') | null;
          };
          id?: string | null;
        }[]
      | null;
    media?: (string | null) | Media;
  };
  layout: (CallToActionBlock | ContentBlock | MediaBlock | ArchiveBlock | FormBlock)[];
  meta?: {
    title?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (string | null) | Media;
    description?: string | null;
  };
  publishedAt?: string | null;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts".
 */
export interface Post {
  id: string;
  title: string;
  /**
   * Arabic title displayed when Arabic language is selected
   */
  titleAr?: string | null;
  date: string;
  author?: string | null;
  featuredImage?: (string | null) | Media;
  media?: (string | Media)[] | null;
  description?: string | null;
  descriptionAr?: string | null;
  heroImage?: (string | null) | Media;
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  /**
   * Arabic content displayed when Arabic language is selected
   */
  contentAr?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  category?: ('news' | 'technology' | 'industry-insights' | 'case-studies' | 'updates') | null;
  tags?: string[] | null;
  relatedPosts?: (string | Post)[] | null;
  categories?: (string | Category)[] | null;
  meta?: {
    title?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (string | null) | Media;
    description?: string | null;
  };
  publishedAt?: string | null;
  authors?: (string | User)[] | null;
  populatedAuthors?:
    | {
        id?: string | null;
        name?: string | null;
      }[]
    | null;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: string;
  alt?: string | null;
  caption?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    square?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    small?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    medium?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    large?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    xlarge?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    og?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: string;
  title: string;
  /**
   * Arabic title displayed when Arabic language is selected
   */
  titleAr?: string | null;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  parent?: (string | null) | Category;
  breadcrumbs?:
    | {
        doc?: (string | null) | Category;
        url?: string | null;
        label?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Admin users. New users will receive an invitation email to set their password. When updating, leave password fields blank to keep current password.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  name: string;
  profilePicture?: (string | null) | Media;
  /**
   * Indicates if the user has set their password
   */
  passwordSet?: boolean | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CallToActionBlock".
 */
export interface CallToActionBlock {
  richText?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  links?:
    | {
        link: {
          type?: ('reference' | 'custom') | null;
          newTab?: boolean | null;
          reference?:
            | ({
                relationTo: 'pages';
                value: string | Page;
              } | null)
            | ({
                relationTo: 'posts';
                value: string | Post;
              } | null);
          url?: string | null;
          label: string;
          /**
           * Arabic label for the link when Arabic language is selected
           */
          labelAr?: string | null;
          /**
           * Choose how the link should be rendered.
           */
          appearance?: ('default' | 'outline') | null;
        };
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'cta';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ContentBlock".
 */
export interface ContentBlock {
  columns?:
    | {
        size?: ('oneThird' | 'half' | 'twoThirds' | 'full') | null;
        richText?: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        enableLink?: boolean | null;
        link?: {
          type?: ('reference' | 'custom') | null;
          newTab?: boolean | null;
          reference?:
            | ({
                relationTo: 'pages';
                value: string | Page;
              } | null)
            | ({
                relationTo: 'posts';
                value: string | Post;
              } | null);
          url?: string | null;
          label: string;
          /**
           * Arabic label for the link when Arabic language is selected
           */
          labelAr?: string | null;
          /**
           * Choose how the link should be rendered.
           */
          appearance?: ('default' | 'outline') | null;
        };
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'content';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "MediaBlock".
 */
export interface MediaBlock {
  media: string | Media;
  id?: string | null;
  blockName?: string | null;
  blockType: 'mediaBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ArchiveBlock".
 */
export interface ArchiveBlock {
  introContent?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  populateBy?: ('collection' | 'selection') | null;
  relationTo?: 'posts' | null;
  categories?: (string | Category)[] | null;
  limit?: number | null;
  selectedDocs?:
    | {
        relationTo: 'posts';
        value: string | Post;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'archive';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FormBlock".
 */
export interface FormBlock {
  form: string | Form;
  enableIntro?: boolean | null;
  introContent?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'formBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "forms".
 */
export interface Form {
  id: string;
  title: string;
  fields?:
    | (
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            defaultValue?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'checkbox';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'country';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'email';
          }
        | {
            message?: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            } | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'message';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'number';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: string | null;
            placeholder?: string | null;
            options?:
              | {
                  label: string;
                  value: string;
                  id?: string | null;
                }[]
              | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'select';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'state';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: string | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'text';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: string | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'textarea';
          }
      )[]
    | null;
  submitButtonLabel?: string | null;
  /**
   * Choose whether to display an on-page message or redirect to a different page after they submit the form.
   */
  confirmationType?: ('message' | 'redirect') | null;
  confirmationMessage?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  redirect?: {
    url: string;
  };
  /**
   * Send custom emails when the form submits. Use comma separated lists to send the same email to multiple recipients. To reference a value from this form, wrap that field's name with double curly brackets, i.e. {{firstName}}. You can use a wildcard {{*}} to output all data and {{*:table}} to format it as an HTML table in the email.
   */
  emails?:
    | {
        emailTo?: string | null;
        cc?: string | null;
        bcc?: string | null;
        replyTo?: string | null;
        emailFrom?: string | null;
        subject: string;
        /**
         * Enter the message that should be sent in this email.
         */
        message?: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services".
 */
export interface Service {
  id: string;
  title: string;
  /**
   * Arabic title displayed when Arabic language is selected
   */
  titleAr?: string | null;
  /**
   * Controls the order/position of this service on the homepage carousel and services page. Lower numbers appear first. If not set, services are sorted by creation date.
   */
  order?: number | null;
  heroImage?: (string | null) | Media;
  heroTitle: string;
  heroTitleAr?: string | null;
  heroDescription?: string | null;
  heroDescriptionAr?: string | null;
  benefits?:
    | {
        title: string;
        titleAr?: string | null;
        description?: string | null;
        descriptionAr?: string | null;
        icon?: (string | null) | Media;
        id?: string | null;
      }[]
    | null;
  applications?:
    | {
        title: string;
        titleAr?: string | null;
        description?: string | null;
        descriptionAr?: string | null;
        image?: (string | null) | Media;
        id?: string | null;
      }[]
    | null;
  technologies?:
    | {
        name: string;
        nameAr?: string | null;
        description?: string | null;
        descriptionAr?: string | null;
        icon?: (string | null) | Media;
        id?: string | null;
      }[]
    | null;
  faqs?:
    | {
        question: string;
        questionAr?: string | null;
        answer: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        };
        answerAr?: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        id?: string | null;
      }[]
    | null;
  ctaTitle?: string | null;
  ctaTitleAr?: string | null;
  ctaDescription?: string | null;
  ctaDescriptionAr?: string | null;
  ctaButtonText?: string | null;
  ctaButtonTextAr?: string | null;
  seo?: {
    title?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (string | null) | Media;
    description?: string | null;
    keywords?: string | null;
  };
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products".
 */
export interface Product {
  id: string;
  name: string;
  /**
   * Arabic product name displayed when Arabic language is selected
   */
  nameAr?: string | null;
  images: (string | Media)[];
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  descriptionAr?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  specifications?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  category: 'drones' | 'payloads' | 'other';
  /**
   * Display tag like "Autonomous Docking", "Enterprise Drones", etc.
   */
  categoryTag?: string | null;
  categoryTagAr?: string | null;
  /**
   * List of key features to display on the product card
   */
  keyFeatures?:
    | {
        feature: string;
        featureAr?: string | null;
        id?: string | null;
      }[]
    | null;
  featured?: boolean | null;
  ctaText?: string | null;
  ctaTextAr?: string | null;
  seo?: {
    title?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (string | null) | Media;
    description?: string | null;
    keywords?: string | null;
  };
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "career".
 */
export interface Career {
  id: string;
  title: string;
  /**
   * Arabic job title displayed when Arabic language is selected
   */
  titleAr?: string | null;
  department: 'engineering' | 'sales' | 'marketing' | 'operations' | 'hr' | 'finance' | 'other';
  location: string;
  locationAr?: string | null;
  employmentType: 'full-time' | 'part-time' | 'contract' | 'internship';
  /**
   * Select the preferred gender for this position (optional)
   */
  gender?: ('male' | 'female' | 'no-preference') | null;
  status: 'draft' | 'published' | 'closed';
  featuredImage?: (string | null) | Media;
  description: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  descriptionAr?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  requirements?:
    | {
        requirement: string;
        requirementAr?: string | null;
        id?: string | null;
      }[]
    | null;
  responsibilities?:
    | {
        responsibility: string;
        responsibilityAr?: string | null;
        id?: string | null;
      }[]
    | null;
  qualifications?:
    | {
        qualification: string;
        qualificationAr?: string | null;
        id?: string | null;
      }[]
    | null;
  salaryRange?: string | null;
  applicationDeadline?: string | null;
  applicationEmail?: string | null;
  applicationUrl?: string | null;
  seo?: {
    title?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (string | null) | Media;
    description?: string | null;
    keywords?: string | null;
  };
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-submissions".
 */
export interface ContactSubmission {
  id: string;
  name: string;
  email: string;
  phone?: string | null;
  company?: string | null;
  subject?: string | null;
  services?: (string | Service)[] | null;
  message: string;
  submittedAt?: string | null;
  status?: ('new' | 'read' | 'replied' | 'archived') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Employee digital profiles for QR code business cards. Each employee gets a unique public URL for their profile. Export to Excel: /api/employees/export (must be logged in).
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "employees".
 */
export interface Employee {
  id: string;
  fullName: string;
  /**
   * Arabic name for profile when user selects Arabic language
   */
  fullNameArabic?: string | null;
  position?: string | null;
  /**
   * Arabic job title for profile when user selects Arabic language
   */
  positionArabic?: string | null;
  profileImage: string | Media;
  phoneNumber: string;
  businessEmail: string;
  /**
   * Full LinkedIn profile URL (e.g. https://linkedin.com/in/username)
   */
  linkedInUrl?: string | null;
  websiteUrl?: string | null;
  /**
   * PDF file - Company profile in Arabic
   */
  companyProfileArabic?: (string | null) | Media;
  /**
   * PDF file - Company profile in English
   */
  companyProfileEnglish?: (string | null) | Media;
  /**
   * Optional: Public folder link containing both Arabic & English PDFs. If set, this will be shown instead of individual PDF buttons.
   */
  companyProfileFolderUrl?: string | null;
  /**
   * Main company website URL (displayed at bottom of profile). Enter with or without https:// (e.g. shamal.sa or https://shamal.sa)
   */
  companyWebsiteUrl?: string | null;
  /**
   * Published profiles are visible on the public QR page
   */
  status: 'draft' | 'published';
  /**
   * Unique URL for profile (used in QR code). Auto-generated on save.
   */
  slug: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "leads".
 */
export interface Lead {
  id: string;
  /**
   * Full name of the lead
   */
  name: string;
  /**
   * Email address of the lead
   */
  email: string;
  /**
   * Phone number of the lead
   */
  phone?: string | null;
  /**
   * Company name
   */
  company?: string | null;
  /**
   * Subject of inquiry
   */
  subject?: string | null;
  /**
   * Services the lead is interested in
   */
  services?: (string | Service)[] | null;
  /**
   * Initial message from the lead
   */
  message: string;
  /**
   * Where was this lead created? Website form triggers ClickUp sync.
   */
  leadOrigin: 'website' | 'admin';
  /**
   * How did this lead find us?
   */
  source?: ('contact-form' | 'phone' | 'email' | 'referral' | 'social-media' | 'other') | null;
  /**
   * Current status of the lead
   */
  status?: ('new' | 'contacted' | 'qualified' | 'proposal-sent' | 'negotiating' | 'won' | 'lost' | 'archived') | null;
  /**
   * Priority level of the lead
   */
  priority?: ('low' | 'medium' | 'high' | 'urgent') | null;
  /**
   * User responsible for following up with this lead
   */
  assignedTo?: (string | null) | User;
  /**
   * Estimated value of this lead in SAR
   */
  estimatedValue?: number | null;
  /**
   * Follow-up activities and notes
   */
  followUps?:
    | {
        /**
         * Date and time of the follow-up
         */
        date: string;
        /**
         * Type of follow-up activity
         */
        type: 'call' | 'email' | 'meeting' | 'proposal' | 'other';
        /**
         * Notes about this follow-up
         */
        notes: string;
        /**
         * Mark as completed
         */
        completed?: boolean | null;
        /**
         * User who completed this follow-up
         */
        completedBy?: (string | null) | User;
        id?: string | null;
      }[]
    | null;
  /**
   * Scheduled date for next follow-up
   */
  nextFollowUpDate?: string | null;
  /**
   * Tags for categorizing leads
   */
  tags?: string[] | null;
  /**
   * Internal notes about this lead
   */
  notes?: string | null;
  /**
   * Whether the initial response email was sent
   */
  emailSent?: boolean | null;
  /**
   * When the initial response email was sent
   */
  emailSentAt?: string | null;
  /**
   * Whether this lead was synced to ClickUp. Use the "Push to ClickUp" button below to sync this lead.
   */
  pushedToClickUp?: boolean | null;
  /**
   * ClickUp task ID (set automatically for website leads)
   */
  clickupTaskId?: string | null;
  /**
   * Link to the ClickUp task
   */
  clickupTaskUrl?: string | null;
  /**
   * When the lead was first submitted
   */
  submittedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "newsletter-subscriptions".
 */
export interface NewsletterSubscription {
  id: string;
  email: string;
  subscribedAt?: string | null;
  status?: ('active' | 'unsubscribed') | null;
  source?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "seo-keywords".
 */
export interface SeoKeyword {
  id: string;
  keyword: string;
  category: 'primary' | 'secondary' | 'long-tail' | 'service-specific' | 'sector-specific';
  description?: string | null;
  relatedPages?:
    | (
        | {
            relationTo: 'pages';
            value: string | Page;
          }
        | {
            relationTo: 'services';
            value: string | Service;
          }
        | {
            relationTo: 'products';
            value: string | Product;
          }
      )[]
    | null;
  priority?: number | null;
  active?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "issue-reports".
 */
export interface IssueReport {
  id: string;
  title?: string | null;
  description: string;
  screenshot?: (string | null) | Media;
  userId: string;
  userName: string;
  userEmail: string;
  status: 'pending' | 'in-progress' | 'resolved' | 'closed';
  adminNotes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "chat-summaries".
 */
export interface ChatSummary {
  id: string;
  userName?: string | null;
  userEmail?: string | null;
  selectedItem?: string | null;
  itemType?: ('service' | 'product' | 'blog' | 'career' | 'support' | 'other') | null;
  conversation?:
    | {
        role: 'user' | 'assistant';
        content: string;
        timestamp: string;
        id?: string | null;
      }[]
    | null;
  keyQuestions?:
    | {
        question: string;
        id?: string | null;
      }[]
    | null;
  finalOutcome?: string | null;
  emailSent?: boolean | null;
  emailSentAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects".
 */
export interface Redirect {
  id: string;
  /**
   * You will need to rebuild the website when changing this field.
   */
  from: string;
  to?: {
    type?: ('reference' | 'custom') | null;
    reference?:
      | ({
          relationTo: 'pages';
          value: string | Page;
        } | null)
      | ({
          relationTo: 'posts';
          value: string | Post;
        } | null);
    url?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "form-submissions".
 */
export interface FormSubmission {
  id: string;
  form: string | Form;
  submissionData?:
    | {
        field: string;
        value: string;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This is a collection of automatically created search results. These results are used by the global site search and will be updated automatically as documents in the CMS are created or updated.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "search".
 */
export interface Search {
  id: string;
  title?: string | null;
  priority?: number | null;
  doc: {
    relationTo: 'posts';
    value: string | Post;
  };
  slug?: string | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    image?: (string | null) | Media;
  };
  categories?:
    | {
        relationTo?: string | null;
        categoryID?: string | null;
        title?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: string;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs".
 */
export interface PayloadJob {
  id: string;
  /**
   * Input data provided to the job
   */
  input?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  taskStatus?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  completedAt?: string | null;
  totalTried?: number | null;
  /**
   * If hasError is true this job will not be retried
   */
  hasError?: boolean | null;
  /**
   * If hasError is true, this is the error that caused it
   */
  error?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Task execution log
   */
  log?:
    | {
        executedAt: string;
        completedAt: string;
        taskSlug: 'inline' | 'schedulePublish';
        taskID: string;
        input?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        output?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        state: 'failed' | 'succeeded';
        error?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        id?: string | null;
      }[]
    | null;
  taskSlug?: ('inline' | 'schedulePublish') | null;
  queue?: string | null;
  waitUntil?: string | null;
  processing?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: 'pages';
        value: string | Page;
      } | null)
    | ({
        relationTo: 'posts';
        value: string | Post;
      } | null)
    | ({
        relationTo: 'media';
        value: string | Media;
      } | null)
    | ({
        relationTo: 'categories';
        value: string | Category;
      } | null)
    | ({
        relationTo: 'users';
        value: string | User;
      } | null)
    | ({
        relationTo: 'services';
        value: string | Service;
      } | null)
    | ({
        relationTo: 'products';
        value: string | Product;
      } | null)
    | ({
        relationTo: 'career';
        value: string | Career;
      } | null)
    | ({
        relationTo: 'contact-submissions';
        value: string | ContactSubmission;
      } | null)
    | ({
        relationTo: 'employees';
        value: string | Employee;
      } | null)
    | ({
        relationTo: 'leads';
        value: string | Lead;
      } | null)
    | ({
        relationTo: 'newsletter-subscriptions';
        value: string | NewsletterSubscription;
      } | null)
    | ({
        relationTo: 'seo-keywords';
        value: string | SeoKeyword;
      } | null)
    | ({
        relationTo: 'issue-reports';
        value: string | IssueReport;
      } | null)
    | ({
        relationTo: 'chat-summaries';
        value: string | ChatSummary;
      } | null)
    | ({
        relationTo: 'redirects';
        value: string | Redirect;
      } | null)
    | ({
        relationTo: 'forms';
        value: string | Form;
      } | null)
    | ({
        relationTo: 'form-submissions';
        value: string | FormSubmission;
      } | null)
    | ({
        relationTo: 'search';
        value: string | Search;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  titleAr?: T;
  hero?:
    | T
    | {
        type?: T;
        richText?: T;
        links?:
          | T
          | {
              link?:
                | T
                | {
                    type?: T;
                    newTab?: T;
                    reference?: T;
                    url?: T;
                    label?: T;
                    labelAr?: T;
                    appearance?: T;
                  };
              id?: T;
            };
        media?: T;
      };
  layout?:
    | T
    | {
        cta?: T | CallToActionBlockSelect<T>;
        content?: T | ContentBlockSelect<T>;
        mediaBlock?: T | MediaBlockSelect<T>;
        archive?: T | ArchiveBlockSelect<T>;
        formBlock?: T | FormBlockSelect<T>;
      };
  meta?:
    | T
    | {
        title?: T;
        image?: T;
        description?: T;
      };
  publishedAt?: T;
  generateSlug?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CallToActionBlock_select".
 */
export interface CallToActionBlockSelect<T extends boolean = true> {
  richText?: T;
  links?:
    | T
    | {
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
              label?: T;
              labelAr?: T;
              appearance?: T;
            };
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ContentBlock_select".
 */
export interface ContentBlockSelect<T extends boolean = true> {
  columns?:
    | T
    | {
        size?: T;
        richText?: T;
        enableLink?: T;
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
              label?: T;
              labelAr?: T;
              appearance?: T;
            };
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "MediaBlock_select".
 */
export interface MediaBlockSelect<T extends boolean = true> {
  media?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ArchiveBlock_select".
 */
export interface ArchiveBlockSelect<T extends boolean = true> {
  introContent?: T;
  populateBy?: T;
  relationTo?: T;
  categories?: T;
  limit?: T;
  selectedDocs?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FormBlock_select".
 */
export interface FormBlockSelect<T extends boolean = true> {
  form?: T;
  enableIntro?: T;
  introContent?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts_select".
 */
export interface PostsSelect<T extends boolean = true> {
  title?: T;
  titleAr?: T;
  date?: T;
  author?: T;
  featuredImage?: T;
  media?: T;
  description?: T;
  descriptionAr?: T;
  heroImage?: T;
  content?: T;
  contentAr?: T;
  category?: T;
  tags?: T;
  relatedPosts?: T;
  categories?: T;
  meta?:
    | T
    | {
        title?: T;
        image?: T;
        description?: T;
      };
  publishedAt?: T;
  authors?: T;
  populatedAuthors?:
    | T
    | {
        id?: T;
        name?: T;
      };
  generateSlug?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        square?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        small?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        medium?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        large?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        xlarge?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        og?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  title?: T;
  titleAr?: T;
  generateSlug?: T;
  slug?: T;
  parent?: T;
  breadcrumbs?:
    | T
    | {
        doc?: T;
        url?: T;
        label?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  profilePicture?: T;
  passwordSet?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services_select".
 */
export interface ServicesSelect<T extends boolean = true> {
  title?: T;
  titleAr?: T;
  order?: T;
  heroImage?: T;
  heroTitle?: T;
  heroTitleAr?: T;
  heroDescription?: T;
  heroDescriptionAr?: T;
  benefits?:
    | T
    | {
        title?: T;
        titleAr?: T;
        description?: T;
        descriptionAr?: T;
        icon?: T;
        id?: T;
      };
  applications?:
    | T
    | {
        title?: T;
        titleAr?: T;
        description?: T;
        descriptionAr?: T;
        image?: T;
        id?: T;
      };
  technologies?:
    | T
    | {
        name?: T;
        nameAr?: T;
        description?: T;
        descriptionAr?: T;
        icon?: T;
        id?: T;
      };
  faqs?:
    | T
    | {
        question?: T;
        questionAr?: T;
        answer?: T;
        answerAr?: T;
        id?: T;
      };
  ctaTitle?: T;
  ctaTitleAr?: T;
  ctaDescription?: T;
  ctaDescriptionAr?: T;
  ctaButtonText?: T;
  ctaButtonTextAr?: T;
  seo?:
    | T
    | {
        title?: T;
        image?: T;
        description?: T;
        keywords?: T;
      };
  generateSlug?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products_select".
 */
export interface ProductsSelect<T extends boolean = true> {
  name?: T;
  nameAr?: T;
  images?: T;
  description?: T;
  descriptionAr?: T;
  specifications?: T;
  category?: T;
  categoryTag?: T;
  categoryTagAr?: T;
  keyFeatures?:
    | T
    | {
        feature?: T;
        featureAr?: T;
        id?: T;
      };
  featured?: T;
  ctaText?: T;
  ctaTextAr?: T;
  seo?:
    | T
    | {
        title?: T;
        image?: T;
        description?: T;
        keywords?: T;
      };
  generateSlug?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "career_select".
 */
export interface CareerSelect<T extends boolean = true> {
  title?: T;
  titleAr?: T;
  department?: T;
  location?: T;
  locationAr?: T;
  employmentType?: T;
  gender?: T;
  status?: T;
  featuredImage?: T;
  description?: T;
  descriptionAr?: T;
  requirements?:
    | T
    | {
        requirement?: T;
        requirementAr?: T;
        id?: T;
      };
  responsibilities?:
    | T
    | {
        responsibility?: T;
        responsibilityAr?: T;
        id?: T;
      };
  qualifications?:
    | T
    | {
        qualification?: T;
        qualificationAr?: T;
        id?: T;
      };
  salaryRange?: T;
  applicationDeadline?: T;
  applicationEmail?: T;
  applicationUrl?: T;
  seo?:
    | T
    | {
        title?: T;
        image?: T;
        description?: T;
        keywords?: T;
      };
  generateSlug?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-submissions_select".
 */
export interface ContactSubmissionsSelect<T extends boolean = true> {
  name?: T;
  email?: T;
  phone?: T;
  company?: T;
  subject?: T;
  services?: T;
  message?: T;
  submittedAt?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "employees_select".
 */
export interface EmployeesSelect<T extends boolean = true> {
  fullName?: T;
  fullNameArabic?: T;
  position?: T;
  positionArabic?: T;
  profileImage?: T;
  phoneNumber?: T;
  businessEmail?: T;
  linkedInUrl?: T;
  websiteUrl?: T;
  companyProfileArabic?: T;
  companyProfileEnglish?: T;
  companyProfileFolderUrl?: T;
  companyWebsiteUrl?: T;
  status?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "leads_select".
 */
export interface LeadsSelect<T extends boolean = true> {
  name?: T;
  email?: T;
  phone?: T;
  company?: T;
  subject?: T;
  services?: T;
  message?: T;
  leadOrigin?: T;
  source?: T;
  status?: T;
  priority?: T;
  assignedTo?: T;
  estimatedValue?: T;
  followUps?:
    | T
    | {
        date?: T;
        type?: T;
        notes?: T;
        completed?: T;
        completedBy?: T;
        id?: T;
      };
  nextFollowUpDate?: T;
  tags?: T;
  notes?: T;
  emailSent?: T;
  emailSentAt?: T;
  pushedToClickUp?: T;
  clickupTaskId?: T;
  clickupTaskUrl?: T;
  submittedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "newsletter-subscriptions_select".
 */
export interface NewsletterSubscriptionsSelect<T extends boolean = true> {
  email?: T;
  subscribedAt?: T;
  status?: T;
  source?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "seo-keywords_select".
 */
export interface SeoKeywordsSelect<T extends boolean = true> {
  keyword?: T;
  category?: T;
  description?: T;
  relatedPages?: T;
  priority?: T;
  active?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "issue-reports_select".
 */
export interface IssueReportsSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  screenshot?: T;
  userId?: T;
  userName?: T;
  userEmail?: T;
  status?: T;
  adminNotes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "chat-summaries_select".
 */
export interface ChatSummariesSelect<T extends boolean = true> {
  userName?: T;
  userEmail?: T;
  selectedItem?: T;
  itemType?: T;
  conversation?:
    | T
    | {
        role?: T;
        content?: T;
        timestamp?: T;
        id?: T;
      };
  keyQuestions?:
    | T
    | {
        question?: T;
        id?: T;
      };
  finalOutcome?: T;
  emailSent?: T;
  emailSentAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects_select".
 */
export interface RedirectsSelect<T extends boolean = true> {
  from?: T;
  to?:
    | T
    | {
        type?: T;
        reference?: T;
        url?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "forms_select".
 */
export interface FormsSelect<T extends boolean = true> {
  title?: T;
  fields?:
    | T
    | {
        checkbox?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              defaultValue?: T;
              id?: T;
              blockName?: T;
            };
        country?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        email?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        message?:
          | T
          | {
              message?: T;
              id?: T;
              blockName?: T;
            };
        number?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        select?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              placeholder?: T;
              options?:
                | T
                | {
                    label?: T;
                    value?: T;
                    id?: T;
                  };
              required?: T;
              id?: T;
              blockName?: T;
            };
        state?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        text?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        textarea?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
      };
  submitButtonLabel?: T;
  confirmationType?: T;
  confirmationMessage?: T;
  redirect?:
    | T
    | {
        url?: T;
      };
  emails?:
    | T
    | {
        emailTo?: T;
        cc?: T;
        bcc?: T;
        replyTo?: T;
        emailFrom?: T;
        subject?: T;
        message?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "form-submissions_select".
 */
export interface FormSubmissionsSelect<T extends boolean = true> {
  form?: T;
  submissionData?:
    | T
    | {
        field?: T;
        value?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "search_select".
 */
export interface SearchSelect<T extends boolean = true> {
  title?: T;
  priority?: T;
  doc?: T;
  slug?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  categories?:
    | T
    | {
        relationTo?: T;
        categoryID?: T;
        title?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs_select".
 */
export interface PayloadJobsSelect<T extends boolean = true> {
  input?: T;
  taskStatus?: T;
  completedAt?: T;
  totalTried?: T;
  hasError?: T;
  error?: T;
  log?:
    | T
    | {
        executedAt?: T;
        completedAt?: T;
        taskSlug?: T;
        taskID?: T;
        input?: T;
        output?: T;
        state?: T;
        error?: T;
        id?: T;
      };
  taskSlug?: T;
  queue?: T;
  waitUntil?: T;
  processing?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header".
 */
export interface Header {
  id: string;
  navItems?:
    | {
        link: {
          type?: ('reference' | 'custom') | null;
          newTab?: boolean | null;
          reference?:
            | ({
                relationTo: 'pages';
                value: string | Page;
              } | null)
            | ({
                relationTo: 'posts';
                value: string | Post;
              } | null);
          url?: string | null;
          label: string;
          /**
           * Arabic label for the link when Arabic language is selected
           */
          labelAr?: string | null;
        };
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer".
 */
export interface Footer {
  id: string;
  navItems?:
    | {
        link: {
          type?: ('reference' | 'custom') | null;
          newTab?: boolean | null;
          reference?:
            | ({
                relationTo: 'pages';
                value: string | Page;
              } | null)
            | ({
                relationTo: 'posts';
                value: string | Post;
              } | null);
          url?: string | null;
          label: string;
          /**
           * Arabic label for the link when Arabic language is selected
           */
          labelAr?: string | null;
        };
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: string;
  siteName: string;
  siteNameAr?: string | null;
  siteDescription?: string | null;
  siteDescriptionAr?: string | null;
  logo?: (string | null) | Media;
  favicon?: (string | null) | Media;
  contactInfo?: {
    phone?: string | null;
    email?: string | null;
    address?: string | null;
    addressAr?: string | null;
    mapEmbedUrl?: string | null;
    mapLink?: string | null;
  };
  socialMedia?: {
    facebook?: string | null;
    twitter?: string | null;
    linkedin?: string | null;
    instagram?: string | null;
    youtube?: string | null;
    tiktok?: string | null;
    snapchat?: string | null;
  };
  footerContent?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  footerContentAr?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "homepage-content".
 */
export interface HomepageContent {
  id: string;
  hero: {
    title: string;
    titleAr?: string | null;
    subtitle?: string | null;
    subtitleAr?: string | null;
    ctaText?: string | null;
    ctaTextAr?: string | null;
    backgroundImage?: (string | null) | Media;
  };
  /**
   * KPI statistics displayed in the "Our Impact" section (e.g. Projects Completed, Client Satisfaction). Drag to reorder.
   */
  impactStats: {
    /**
     * Small label above the heading (e.g. "Our Impact")
     */
    badge?: string | null;
    badgeAr?: string | null;
    /**
     * Main heading for the stats section
     */
    heading?: string | null;
    headingAr?: string | null;
    /**
     * Add statistics. Each has a numeric value, optional suffix (%, +), and label. Drag to reorder.
     */
    stats: {
      /**
       * The numeric value to display (e.g. 100, 80, 11)
       */
      value: number;
      /**
       * Optional suffix after the number (e.g. % for percentage, + for "more than")
       */
      suffix?: ('' | '%' | '+') | null;
      /**
       * Optional prefix before the number (e.g. + for "+80")
       */
      prefix?: ('' | '+') | null;
      /**
       * Description below the number (e.g. "Projects Completed", "Client Satisfaction")
       */
      label: string;
      labelAr?: string | null;
      id?: string | null;
    }[];
  };
  servicesOverview?: {
    title?: string | null;
    titleAr?: string | null;
    description?: string | null;
    descriptionAr?: string | null;
    backgroundImage?: (string | null) | Media;
  };
  sectors?: {
    /**
     * Small label above the section title (e.g. "Industries")
     */
    badge?: string | null;
    badgeAr?: string | null;
    title?: string | null;
    titleAr?: string | null;
    description?: string | null;
    descriptionAr?: string | null;
    backgroundImage?: (string | null) | Media;
    /**
     * Select and reorder sectors to display on the homepage. Drag items to change the sequence. If empty, all sectors will be displayed in their default order.
     */
    selectedSectors?:
      | {
          /**
           * Select a sector to display. The order in this list determines the display order on the homepage.
           */
          sectorSlug:
            | 'government'
            | 'transportation'
            | 'mining'
            | 'construction'
            | 'real-estate'
            | 'education'
            | 'oil-gas'
            | 'heritage'
            | 'marine'
            | 'agriculture'
            | 'utilities'
            | 'environment'
            | 'application-development'
            | 'app-development';
          id?: string | null;
        }[]
      | null;
  };
  aboutPreview: {
    badge?: string | null;
    badgeAr?: string | null;
    title: string;
    titleAr?: string | null;
    /**
     * Description text displayed below the heading
     */
    description?: string | null;
    descriptionAr?: string | null;
    /**
     * Image or video to display in the left column below the description
     */
    imageColumn?: (string | null) | Media;
    /**
     * Rich text content to display in the right column below the description. Use headings, paragraphs, and bullet lists.
     */
    textColumn?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
    textColumnAr?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
    /**
     * Enable to show image/video on left and text on right below the description
     */
    enableTwoColumn?: boolean | null;
    /**
     * Image or video to display on the left side
     */
    leftColumnMedia?: (string | null) | Media;
    /**
     * Add text blocks with different types (heading, bullets, paragraph)
     */
    rightColumnTextBlocks?:
      | {
          textType: 'heading' | 'paragraph' | 'bullets';
          heading?: string | null;
          headingAr?: string | null;
          headingLevel?: ('h2' | 'h3' | 'h4') | null;
          paragraph?: string | null;
          paragraphAr?: string | null;
          bullets?:
            | {
                text: string;
                textAr?: string | null;
                id?: string | null;
              }[]
            | null;
          id?: string | null;
        }[]
      | null;
    ctaText?: string | null;
    ctaTextAr?: string | null;
    backgroundImage?: (string | null) | Media;
  };
  blogPreview?: {
    title?: string | null;
    titleAr?: string | null;
    description?: string | null;
    descriptionAr?: string | null;
    ctaText?: string | null;
    ctaTextAr?: string | null;
    backgroundImage?: (string | null) | Media;
    /**
     * Select specific blog posts to display on homepage. If empty, latest posts will be shown.
     */
    featuredPosts?:
      | {
          post: string | Post;
          /**
           * Override the post featured image with a custom image for homepage display
           */
          customImage?: (string | null) | Media;
          id?: string | null;
        }[]
      | null;
  };
  contactCTA?: {
    /**
     * Small label above the heading
     */
    badge?: string | null;
    badgeAr?: string | null;
    title?: string | null;
    titleAr?: string | null;
    description?: string | null;
    descriptionAr?: string | null;
    /**
     * Main CTA button (e.g. "Contact Us Today")
     */
    ctaText?: string | null;
    ctaTextAr?: string | null;
    secondaryCtaText?: string | null;
    secondaryCtaTextAr?: string | null;
    backgroundImage?: (string | null) | Media;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about-page-content".
 */
export interface AboutPageContent {
  id: string;
  hero: {
    /**
     * Small label above the title (e.g. "Our Story")
     */
    badge?: string | null;
    badgeAr?: string | null;
    title: string;
    titleAr?: string | null;
    description?: string | null;
    descriptionAr?: string | null;
    /**
     * Upload an image for the hero background. If no image is uploaded, the video will be used as fallback.
     */
    image?: (string | null) | Media;
    /**
     * Upload a video for the hero background. Video will be used if no image is uploaded. Recommended: MP4 format, optimized for web.
     */
    video?: (string | null) | Media;
  };
  vision?: {
    title?: string | null;
    titleAr?: string | null;
    description?: string | null;
    descriptionAr?: string | null;
    content?: string | null;
    contentAr?: string | null;
    image?: (string | null) | Media;
  };
  mission?: {
    title?: string | null;
    titleAr?: string | null;
    description?: string | null;
    descriptionAr?: string | null;
    content?: string | null;
    contentAr?: string | null;
    image?: (string | null) | Media;
  };
  whyChooseUs?: {
    /**
     * Small label above the main heading (e.g. "Advantages")
     */
    badge?: string | null;
    /**
     * Arabic text for the badge when Arabic language is selected
     */
    badgeAr?: string | null;
    title?: string | null;
    titleAr?: string | null;
    subtitle?: string | null;
    subtitleAr?: string | null;
    items?:
      | {
          title: string;
          titleAr?: string | null;
          description?: string | null;
          descriptionAr?: string | null;
          /**
           * Alternative to description field
           */
          content?: string | null;
          contentAr?: string | null;
          /**
           * Image displayed in the sticky right column (desktop)
           */
          image?: (string | null) | Media;
          id?: string | null;
        }[]
      | null;
  };
  certifications?:
    | {
        name: string;
        nameAr?: string | null;
        image?: (string | null) | Media;
        description?: string | null;
        descriptionAr?: string | null;
        id?: string | null;
      }[]
    | null;
  achievements?:
    | {
        title: string;
        titleAr?: string | null;
        description?: string | null;
        descriptionAr?: string | null;
        icon?: (string | null) | Media;
        id?: string | null;
      }[]
    | null;
  timeline?:
    | {
        year: number;
        title: string;
        titleAr?: string | null;
        description?: string | null;
        descriptionAr?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Badge, title, and description for the Leadership/Meet the Team section.
   */
  leadershipSection?: {
    /**
     * Small label above the section title (e.g. "OUR PEOPLE")
     */
    badge?: string | null;
    badgeAr?: string | null;
    /**
     * Main heading for the leadership section
     */
    title?: string | null;
    titleAr?: string | null;
    /**
     * Introductory text below the title
     */
    description?: string | null;
    descriptionAr?: string | null;
  };
  /**
   * Team members displayed in the carousel. Each member has name, position, bio, and optional image.
   */
  leadership?:
    | {
        name: string;
        nameAr?: string | null;
        position: string;
        positionAr?: string | null;
        /**
         * Bio content should not exceed 700 characters. Characters remaining will be shown as you type.
         */
        bio?: string | null;
        /**
         * Bio content should not exceed 700 characters for Arabic.
         */
        bioAr?: string | null;
        image?: (string | null) | Media;
        id?: string | null;
      }[]
    | null;
  /**
   * Badge, title, and description for the Clients/Partners section.
   */
  clientsSection?: {
    /**
     * Small label above the section title (e.g. "Partners")
     */
    badge?: string | null;
    badgeAr?: string | null;
    /**
     * Main heading for the clients section
     */
    title?: string | null;
    titleAr?: string | null;
    /**
     * Introductory text below the title
     */
    description?: string | null;
    descriptionAr?: string | null;
  };
  /**
   * Client logos displayed in the infinite logo section on the homepage and about page. Only images are needed. You can add unlimited client logos.
   */
  clients?:
    | {
        logo: string | Media;
        id?: string | null;
      }[]
    | null;
  /**
   * Client testimonials with name, image, and review text.
   */
  testimonials?:
    | {
        name: string;
        nameAr?: string | null;
        image: string | Media;
        review: string;
        reviewAr?: string | null;
        id?: string | null;
      }[]
    | null;
  strengths?:
    | {
        title: string;
        titleAr?: string | null;
        description?: string | null;
        descriptionAr?: string | null;
        icon?: (string | null) | Media;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts-page-content".
 */
export interface PostsPageContent {
  id: string;
  hero: {
    /**
     * Small label above the title
     */
    badge?: string | null;
    badgeAr?: string | null;
    title: string;
    titleAr?: string | null;
    /**
     * Subtitle or description for the blog posts page
     */
    description?: string | null;
    descriptionAr?: string | null;
    backgroundImage?: (string | null) | Media;
  };
  seo?: {
    /**
     * SEO title for the blog posts page
     */
    metaTitle?: string | null;
    /**
     * SEO meta description for the blog posts page
     */
    metaDescription?: string | null;
    /**
     * Social sharing image (1200x630px recommended)
     */
    ogImage?: (string | null) | Media;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "careers-page-content".
 */
export interface CareersPageContent {
  id: string;
  hero: {
    /**
     * Small label above the title
     */
    badge?: string | null;
    badgeAr?: string | null;
    title: string;
    titleAr?: string | null;
    /**
     * Subtitle or description for the careers page
     */
    description?: string | null;
    descriptionAr?: string | null;
    backgroundImage?: (string | null) | Media;
  };
  seo?: {
    /**
     * SEO title for the careers page
     */
    metaTitle?: string | null;
    /**
     * SEO meta description for the careers page
     */
    metaDescription?: string | null;
    /**
     * Social sharing image (1200x630px recommended)
     */
    ogImage?: (string | null) | Media;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-page-content".
 */
export interface ContactPageContent {
  id: string;
  hero: {
    /**
     * Small label above the title
     */
    badge?: string | null;
    badgeAr?: string | null;
    title: string;
    titleAr?: string | null;
    /**
     * Subtitle or description for the contact page
     */
    subtitle?: string | null;
    subtitleAr?: string | null;
    backgroundImage?: (string | null) | Media;
  };
  seo?: {
    /**
     * SEO title for the contact page
     */
    metaTitle?: string | null;
    /**
     * SEO meta description for the contact page
     */
    metaDescription?: string | null;
    /**
     * Social sharing image (1200x630px recommended)
     */
    ogImage?: (string | null) | Media;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products-page-content".
 */
export interface ProductsPageContent {
  id: string;
  hero: {
    /**
     * Small label above the title
     */
    badge?: string | null;
    badgeAr?: string | null;
    title: string;
    titleAr?: string | null;
    /**
     * Subtitle or description for the products page
     */
    subtitle?: string | null;
    subtitleAr?: string | null;
    backgroundImage?: (string | null) | Media;
  };
  seo?: {
    /**
     * SEO title for the products page
     */
    metaTitle?: string | null;
    /**
     * SEO meta description for the products page
     */
    metaDescription?: string | null;
    /**
     * Social sharing image (1200x630px recommended)
     */
    ogImage?: (string | null) | Media;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services-page-content".
 */
export interface ServicesPageContent {
  id: string;
  hero: {
    /**
     * Small label above the title (e.g. "Our Services")
     */
    badge?: string | null;
    badgeAr?: string | null;
    title: string;
    titleAr?: string | null;
    /**
     * Subtitle or description for the services page
     */
    subtitle?: string | null;
    subtitleAr?: string | null;
    backgroundImage?: (string | null) | Media;
  };
  seo?: {
    /**
     * SEO title for the services page
     */
    metaTitle?: string | null;
    /**
     * SEO meta description for the services page
     */
    metaDescription?: string | null;
    /**
     * Social sharing image (1200x630px recommended)
     */
    ogImage?: (string | null) | Media;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sectors-content".
 */
export interface SectorsContent {
  id: string;
  sectors?:
    | {
        name: string;
        nameAr?: string | null;
        slug: string;
        description?: string | null;
        descriptionAr?: string | null;
        image?: (string | null) | Media;
        /**
         * Link to blog page or section
         */
        ctaBlog?: string | null;
        /**
         * Link to contact page or section
         */
        ctaContact?: string | null;
        useCases?:
          | {
              title: string;
              titleAr?: string | null;
              description?: string | null;
              descriptionAr?: string | null;
              id?: string | null;
            }[]
          | null;
        solutionsDelivered?:
          | {
              title: string;
              titleAr?: string | null;
              description?: string | null;
              descriptionAr?: string | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "seo-settings".
 */
export interface SeoSetting {
  id: string;
  primaryKeywords?: string[] | null;
  secondaryKeywords?: string[] | null;
  longTailKeywords?: string[] | null;
  serviceKeywords?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  sectorKeywords?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  metaDescriptionTemplate?: string | null;
  ogImageDefault?: (string | null) | Media;
  twitterCardDefault?: (string | null) | Media;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header_select".
 */
export interface HeaderSelect<T extends boolean = true> {
  navItems?:
    | T
    | {
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
              label?: T;
              labelAr?: T;
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer_select".
 */
export interface FooterSelect<T extends boolean = true> {
  navItems?:
    | T
    | {
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
              label?: T;
              labelAr?: T;
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  siteName?: T;
  siteNameAr?: T;
  siteDescription?: T;
  siteDescriptionAr?: T;
  logo?: T;
  favicon?: T;
  contactInfo?:
    | T
    | {
        phone?: T;
        email?: T;
        address?: T;
        addressAr?: T;
        mapEmbedUrl?: T;
        mapLink?: T;
      };
  socialMedia?:
    | T
    | {
        facebook?: T;
        twitter?: T;
        linkedin?: T;
        instagram?: T;
        youtube?: T;
        tiktok?: T;
        snapchat?: T;
      };
  footerContent?: T;
  footerContentAr?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "homepage-content_select".
 */
export interface HomepageContentSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        title?: T;
        titleAr?: T;
        subtitle?: T;
        subtitleAr?: T;
        ctaText?: T;
        ctaTextAr?: T;
        backgroundImage?: T;
      };
  impactStats?:
    | T
    | {
        badge?: T;
        badgeAr?: T;
        heading?: T;
        headingAr?: T;
        stats?:
          | T
          | {
              value?: T;
              suffix?: T;
              prefix?: T;
              label?: T;
              labelAr?: T;
              id?: T;
            };
      };
  servicesOverview?:
    | T
    | {
        title?: T;
        titleAr?: T;
        description?: T;
        descriptionAr?: T;
        backgroundImage?: T;
      };
  sectors?:
    | T
    | {
        badge?: T;
        badgeAr?: T;
        title?: T;
        titleAr?: T;
        description?: T;
        descriptionAr?: T;
        backgroundImage?: T;
        selectedSectors?:
          | T
          | {
              sectorSlug?: T;
              id?: T;
            };
      };
  aboutPreview?:
    | T
    | {
        badge?: T;
        badgeAr?: T;
        title?: T;
        titleAr?: T;
        description?: T;
        descriptionAr?: T;
        imageColumn?: T;
        textColumn?: T;
        textColumnAr?: T;
        enableTwoColumn?: T;
        leftColumnMedia?: T;
        rightColumnTextBlocks?:
          | T
          | {
              textType?: T;
              heading?: T;
              headingAr?: T;
              headingLevel?: T;
              paragraph?: T;
              paragraphAr?: T;
              bullets?:
                | T
                | {
                    text?: T;
                    textAr?: T;
                    id?: T;
                  };
              id?: T;
            };
        ctaText?: T;
        ctaTextAr?: T;
        backgroundImage?: T;
      };
  blogPreview?:
    | T
    | {
        title?: T;
        titleAr?: T;
        description?: T;
        descriptionAr?: T;
        ctaText?: T;
        ctaTextAr?: T;
        backgroundImage?: T;
        featuredPosts?:
          | T
          | {
              post?: T;
              customImage?: T;
              id?: T;
            };
      };
  contactCTA?:
    | T
    | {
        badge?: T;
        badgeAr?: T;
        title?: T;
        titleAr?: T;
        description?: T;
        descriptionAr?: T;
        ctaText?: T;
        ctaTextAr?: T;
        secondaryCtaText?: T;
        secondaryCtaTextAr?: T;
        backgroundImage?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about-page-content_select".
 */
export interface AboutPageContentSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        badge?: T;
        badgeAr?: T;
        title?: T;
        titleAr?: T;
        description?: T;
        descriptionAr?: T;
        image?: T;
        video?: T;
      };
  vision?:
    | T
    | {
        title?: T;
        titleAr?: T;
        description?: T;
        descriptionAr?: T;
        content?: T;
        contentAr?: T;
        image?: T;
      };
  mission?:
    | T
    | {
        title?: T;
        titleAr?: T;
        description?: T;
        descriptionAr?: T;
        content?: T;
        contentAr?: T;
        image?: T;
      };
  whyChooseUs?:
    | T
    | {
        badge?: T;
        badgeAr?: T;
        title?: T;
        titleAr?: T;
        subtitle?: T;
        subtitleAr?: T;
        items?:
          | T
          | {
              title?: T;
              titleAr?: T;
              description?: T;
              descriptionAr?: T;
              content?: T;
              contentAr?: T;
              image?: T;
              id?: T;
            };
      };
  certifications?:
    | T
    | {
        name?: T;
        nameAr?: T;
        image?: T;
        description?: T;
        descriptionAr?: T;
        id?: T;
      };
  achievements?:
    | T
    | {
        title?: T;
        titleAr?: T;
        description?: T;
        descriptionAr?: T;
        icon?: T;
        id?: T;
      };
  timeline?:
    | T
    | {
        year?: T;
        title?: T;
        titleAr?: T;
        description?: T;
        descriptionAr?: T;
        id?: T;
      };
  leadershipSection?:
    | T
    | {
        badge?: T;
        badgeAr?: T;
        title?: T;
        titleAr?: T;
        description?: T;
        descriptionAr?: T;
      };
  leadership?:
    | T
    | {
        name?: T;
        nameAr?: T;
        position?: T;
        positionAr?: T;
        bio?: T;
        bioAr?: T;
        image?: T;
        id?: T;
      };
  clientsSection?:
    | T
    | {
        badge?: T;
        badgeAr?: T;
        title?: T;
        titleAr?: T;
        description?: T;
        descriptionAr?: T;
      };
  clients?:
    | T
    | {
        logo?: T;
        id?: T;
      };
  testimonials?:
    | T
    | {
        name?: T;
        nameAr?: T;
        image?: T;
        review?: T;
        reviewAr?: T;
        id?: T;
      };
  strengths?:
    | T
    | {
        title?: T;
        titleAr?: T;
        description?: T;
        descriptionAr?: T;
        icon?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts-page-content_select".
 */
export interface PostsPageContentSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        badge?: T;
        badgeAr?: T;
        title?: T;
        titleAr?: T;
        description?: T;
        descriptionAr?: T;
        backgroundImage?: T;
      };
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        ogImage?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "careers-page-content_select".
 */
export interface CareersPageContentSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        badge?: T;
        badgeAr?: T;
        title?: T;
        titleAr?: T;
        description?: T;
        descriptionAr?: T;
        backgroundImage?: T;
      };
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        ogImage?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-page-content_select".
 */
export interface ContactPageContentSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        badge?: T;
        badgeAr?: T;
        title?: T;
        titleAr?: T;
        subtitle?: T;
        subtitleAr?: T;
        backgroundImage?: T;
      };
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        ogImage?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products-page-content_select".
 */
export interface ProductsPageContentSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        badge?: T;
        badgeAr?: T;
        title?: T;
        titleAr?: T;
        subtitle?: T;
        subtitleAr?: T;
        backgroundImage?: T;
      };
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        ogImage?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services-page-content_select".
 */
export interface ServicesPageContentSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        badge?: T;
        badgeAr?: T;
        title?: T;
        titleAr?: T;
        subtitle?: T;
        subtitleAr?: T;
        backgroundImage?: T;
      };
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        ogImage?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sectors-content_select".
 */
export interface SectorsContentSelect<T extends boolean = true> {
  sectors?:
    | T
    | {
        name?: T;
        nameAr?: T;
        slug?: T;
        description?: T;
        descriptionAr?: T;
        image?: T;
        ctaBlog?: T;
        ctaContact?: T;
        useCases?:
          | T
          | {
              title?: T;
              titleAr?: T;
              description?: T;
              descriptionAr?: T;
              id?: T;
            };
        solutionsDelivered?:
          | T
          | {
              title?: T;
              titleAr?: T;
              description?: T;
              descriptionAr?: T;
              id?: T;
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "seo-settings_select".
 */
export interface SeoSettingsSelect<T extends boolean = true> {
  primaryKeywords?: T;
  secondaryKeywords?: T;
  longTailKeywords?: T;
  serviceKeywords?: T;
  sectorKeywords?: T;
  metaDescriptionTemplate?: T;
  ogImageDefault?: T;
  twitterCardDefault?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskSchedulePublish".
 */
export interface TaskSchedulePublish {
  input: {
    type?: ('publish' | 'unpublish') | null;
    locale?: string | null;
    doc?:
      | ({
          relationTo: 'pages';
          value: string | Page;
        } | null)
      | ({
          relationTo: 'posts';
          value: string | Post;
        } | null);
    global?: string | null;
    user?: (string | null) | User;
  };
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "BannerBlock".
 */
export interface BannerBlock {
  style: 'info' | 'warning' | 'error' | 'success';
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'banner';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CodeBlock".
 */
export interface CodeBlock {
  language?: ('typescript' | 'javascript' | 'css') | null;
  code: string;
  id?: string | null;
  blockName?: string | null;
  blockType: 'code';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}